VERSION --allow-without-earthly-labels 0.8

## ---------------------------------------------
## We want Earthly to be as reproducible as possible,
## so we'll pass every argument at build.
## All those would be in the .arg file
ARG --global  BUSYBOX_TAG='latest'
FROM busybox:${BUSYBOX_TAG} ## BUSYBOX_VERSION

ARG --global  BASE_IMAGE='ubuntu'
ARG --global  BASE_TAG='jammy'

ARG --global PATCH='listen_notify' # Will apply everything in the order that the list is returned
# ARG --global POSTGRES_BRANCH='REL_17_STABLE'
ARG --global POSTGRES_BRANCH='master'
ARG --global PG_REPOSITORY='https://github.com/postgres/postgres.git'
ARG --global PG_SRC='/src/postgres'
ARG --global PREFIX='/usr/local/postgres'


build-all:
    BUILD +build-w-patch
    BUILD +build-vanilla

dependencies:
    FROM ${BASE_IMAGE}:${BASE_TAG}
    DO ./${BASE_IMAGE}/${BASE_TAG}+INSTALL_DEPS

    SAVE IMAGE --cache-hint

clone:
    FROM +dependencies
    
    GIT CLONE --branch ${POSTGRES_BRANCH} ${PG_REPOSITORY} ${PG_SRC}

    WORKDIR ${PG_SRC}
    SAVE IMAGE --cache-hint  

build-w-patch:
    FROM +clone

    COPY ./patches/${PATCH}/*.patch ./

    FOR patch IN $(ls *.patch)
        RUN patch -p1 < "${patch}"
    END

    DO --pass-args ./${BASE_IMAGE}/${BASE_TAG}+COMPILE

    RUN useradd postgres  && usermod -a -G postgres postgres
    RUN chown -R postgres: ${PREFIX}
    RUN chown -R postgres: ${PG_SRC}
    USER postgres
    ENV LANG en_US.utf8
    ENV LC_ALL en_US.utf8
    ENV LC_CTYPE en_US.utf8
    
    DO --pass-args ./${BASE_IMAGE}/${BASE_TAG}+INSTALLCHECK

build-vanilla:
    FROM +clone
    USER postgres
    DO --pass-args ./${BASE_IMAGE}/${BASE_TAG}+COMPILE
    # DO --pass-args ./${BASE_IMAGE}/${BASE_TAG}+INSTALLCHECK
