VERSION --allow-without-earthly-labels 0.8

ARG --global MAX_JOBS=${MAX_JOBS:-4}
ARG --global PG_SRC
ARG --global PREFIX

INSTALL_DEPS:
    FUNCTION
    RUN set -ex; \
        apt update

    RUN set -ex ; \
        DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
        build-essential flex libxml2-dev libxml2-utils libc6-dev \
        libxslt-dev \
        libreadline-dev zlib1g-dev libldap2-dev libpam0g-dev gettext  \
        uuid uuid-dev cmake lld apt-utils pkg-config libossp-uuid-dev gnulib bison git

    ## XXX implement IF jammy for the below statements, support focal would be 
    ## changing libicu66 and python-dev
    RUN set -ex ; \
        DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
        xsltproc icu-devtools libicu70 libicu-dev gawk curl

    RUN set -ex ; \
        DEBIAN_FRONTEND=noninteractive \
        apt install -y openjdk-8-jre openssl \
            libssl-dev libpq-dev \
            pkgconf unzip libutfcpp-dev gnupg \
            python-dev-is-python3

    RUN rm -rf /var/lib/apt/lists/*; \
        apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false;
    
## ---------------------------------------------
## XXX All the below functions are quite standard across
## OS flavors, so they would be potentially move into a
## library in the parent directory.

COMPILE:
    FUNCTION
    ARG TARGETARG

    IF [ "${TARGETARCH}" = "amd64" ]
      ENV CFLAGS_ARG='${CFLAGS:--Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic}' 

    ELSE IF [ "${TARGETARCH}" = "arm64" ]
      ENV CFLAGS_ARG="-ggdb " 
      ENV CONFIGURE_FLAGS=' --build=arm-linux-gnueabihf '
    END

    RUN ./configure CFLAGS="${CFLAGS_ARG}" \
            --enable-debug \
            --enable-cassert \
            --with-ldap \
            --with-libxml \
            --with-pam \
            --with-uuid=ossp \
            --enable-nls \
            --with-libxslt \
            # --enable-tap-tests \
            --with-icu "${CONFIGURE_FLAGS}"
    

    RUN make clean && make prefix=${PREFIX} -j ${MAX_JOBS} world-bin && make prefix=${PREFIX} install
    WORKDIR ./contrib
    RUN make 
    RUN make prefix=${PREFIX} install
    WORKDIR ${PG_SRC}
    # RUN true

INSTALLCHECK:
    FUNCTION

    RUN make  destdir="${PREFIX}/tmp_install" EXTRA_REGRESS_OPTS=--debug -j ${MAX_JOBS} check